server:
  port: 9539

spring:
  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/gtsf_iberoarq?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: gtsf_iberoArqUsr
    password: El.4dministra

  # JPA
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
    open-in-view: false
  # Spring Boot banner
  banner:
    location: classpath:/banner/banner.txt

  #Thymeleaf
  thymeleaf:
    cache: false

  # Upload file properties
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB